### ISSUE TITLE
Duplicated callback

### ISSUE THREAD

**Issue by Ying1986** [MortimerGoro/MGSwipeTableCell#160]
[MGSwipeButton buttonWithTitle:@"More" backgroundColor:[UIColor lightGrayColor] callback:^BOOL(MGSwipeTableCell *sender) {
      NSLog(@"Convenience callback for swipe buttons!");
}]

This callback function is called several times when I click the button.
"Convenience callback for swipe buttons! appear multi time"
"Convenience callback for swipe buttons! appear multi time"
...

-(instancetype) initWithButtons:(NSArray*) buttonsArray direction:(MGSwipeDirection) direction differentWidth:(BOOL) differentWidth
that function is called several times when swipe tableviewceill without click swipe button.

![screen shot 2015-11-12 at 4 40 18 pm](https://cloud.githubusercontent.com/assets/6648212/11122654/6ef54d22-895c-11e5-8d9c-5dcc5c7b15a3.png)

@MortimerGoro

**Comment by hagile** [comment]
+1 same issue

**Comment by MortimerGoro** [comment]
Fixed in 353902c. It will be available in 1.5.2 release

**Comment by hagile** [comment]
@MortimerGoro, thanks for the quick response but it still not resolved.

**Comment by Ying1986** [comment]
Thank you for reply @MortimerGoro 

But it it is not resolved.

MGSwipeTableCell.m : 289
-(void) buttonClicked: (id) sender
{
    [self handleClick:sender fromExpansion:NO];
}

This function is called 1+ times.

As I said,
 -(instancetype) initWithButtons:(NSArray*) buttonsArray direction:(MGSwipeDirection) direction differentWidth:(BOOL) differentWidth
is called 1+ times.

so, line: 90
                if (![[(UIButton *) button allTargets] containsObject:self]) {
                    [(UIButton *)button addTarget:self action:@selector(buttonClicked:) forControlEvents:UIControlEventTouchUpInside];
                }
is called 1+ times, so one button has several action for one event.

Please check it.

Regards

**Comment by MortimerGoro** [comment]
It should be fixed in 1.5.3, I remove all the previous buttonClicked selectors now when the new selector is added.

**Comment by Ying1986** [comment]
@MortimerGoro 

Please check again.

`                for (id target in btn.allTargets) {
                    if ([target isKindOfClass:self.class]) {
                        [btn removeTarget:target action:@selector(buttonClicked:) forControlEvents:UIControlEventTouchUpInside]; //Remove all targets to avoid problems with reused buttons among many cells
                    }`

It is not called, please check again and fix it. :-1:
