### ISSUE TITLE
Big problem with devices that read right to left (Arabic and Hebrew) - iOS9 - AccessoryView to the Left

### ISSUE THREAD

**Issue by waelsaad** [MortimerGoro/MGSwipeTableCell#168]
Hi,

I love this control its great and I wish you help fix the issue of aligning the buttons correctly on iOS9 if you have a UITableViewCell like in the pic below:

The issue usually happens when you switch the device language to either Arabic or Hebrew. The problem is that the AccessoryView is on the left not on the right so the ContentViewCell already starts with an offset of 47 and does not start at zero. 

This causes MGSwipeTableCell to stuff up completely.

I have tried my best to fix the problem but I am still getting glitches of wrong button start and finish offsets .

![untitled1](https://cloud.githubusercontent.com/assets/4057766/11546519/f22a7370-99a1-11e5-9ee2-4a3b777a0d78.png)

Thank you.

Will

**Comment by waelsaad** [comment]
Any suggestions / response please. Thanks

**Comment by hashier** [comment]
I can tell you how we "fixed" it.

We use MGSwipeTable for iOS 7 and for iOS 8 and 9 we use native. So we check the system during `tableView:cellForRowAtIndexPath:` and then either seit the delegate of the cell to self if it is iOS 7 or just skip it and go with the delegate methods of the tableView for swiping, like `tableView:canEditRowAtIndexPath:`

**Comment by waelsaad** [comment]
Thanks for the response, I am just wondering if you have a simple demo of this?

**Comment by hashier** [comment]
As said before, nothing fancy:

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
...
        if (SYSTEM_VERSION_LESS_THAN(@"8.0")) { // for iOS 7 devices, we will use MGSwipeTableCell for presenting action buttons in the cell
            cell.delegate = self;
            cell.rightSwipeSettings.transition = MGSwipeTransitionStatic;
        }
...
}
```

```
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (SYSTEM_VERSION_LESS_THAN(@"8.0")) {
        return NO;
    }
...
```

```
- (nullable NSArray<UITableViewRowAction *> *)tableView:(UITableView *)tableView editActionsForRowAtIndexPath:(NSIndexPath *)indexPath
{
    if (SYSTEM_VERSION_LESS_THAN(@"8.0")) { // for iOS 7 devices, we will use MGSwipeTableCell for presenting action buttons in the cell
        return nil;
    }
...
```

and so on, and then implement both delegates, the ones directly from apple and the ones from MGSwipeTableCell.

**Comment by MortimerGoro** [comment]
Fixed in 1.5.4 ;)

**Comment by kittany13** [comment]
hello there... i still have this issue: white space from the right in right to left language direction
 in 1.5.5 v, tested in iphone 6 device, ios 9.3.3
![img_1882](https://cloud.githubusercontent.com/assets/8138261/17276687/0e0f2da6-5739-11e6-8f1e-696be3454ceb.PNG)
