### ISSUE TITLE
Can not swipe in Xcode 9 swift 4, but demo ok

### ISSUE THREAD

**Issue by JenkinDU** [MortimerGoro/MGSwipeTableCell#296]
I don't know why, I migrate my code from swift 3 to 4, build by sdk11, it's not working now
did someone has this issues?

**Comment by alexvazquez** [comment]
I was going to upgrade my project to Swift 4 from 3 but was good I saw your issue. Did you solved it? Thanks

**Comment by JenkinDU** [comment]
not now, I will check is there some bad code in my project, the demo is ok, you can try in your code

**Comment by JenkinDU** [comment]
Hi, I fixed the bug, the reason is in "swipeTableCell(_ cell: MGSwipeTableCell, swipeButtonsFor direction: MGSwipeDirection, swipeSettings: MGSwipeSettings, expansionSettings: MGSwipeExpansionSettings)" function I return [Any], here has to return [UIView]

**Comment by ukmarn** [comment]
@jenkindu Hey there, I am having the same issue. I am returning two MGSwipeButton inside swipeTableCell swipeButtonsFor function but still cannot swipe. Also tried creating custom UIView with some background color just to test it out and still no luck. I can see that function gets called but still cannot swipe / display buttons.
